### ISSUE TITLE
Reducing the size of the wasm file

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/xeus-lua-kernel#16]
The current wasm file is about 40MB which is quite huge.

Wondering whether there would be a way to reduce the size. Maybe that would involve passing a couple of flags to the emscripten build command.

**Comment by DerThorsten** [comment]
I am very sure we can get the size smaller...so far 0 attempts of me have been made to reduce the size, but I can look into this now

**Comment by DerThorsten** [comment]
down to 6 Mb
